// @ts-nocheck
/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, NetworkOnly } from 'workbox-strategies'
import { ExpirationPlugin } from 'workbox-expiration'
import { BackgroundSyncPlugin } from 'workbox-background-sync'

declare let self: ServiceWorkerGlobalScope

self.skipWaiting()
clientsClaim()

cleanupOutdatedCaches()

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST)

// Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 })
    ]
  })
)

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 365 * 24 * 60 * 60 })
    ]
  })
)

// Supabase GET requests
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 24 * 60 * 60 })
    ]
  }),
  'GET'
)

// Supabase Functions
registerRoute(
  /^https:\/\/.*\.supabase\.co\/functions\/v1\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-functions-cache',
    networkTimeoutSeconds: 5,
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 })
    ]
  }),
  'GET'
)

// Background Sync for Mutations
// This creates a queue that replays failed requests when the network returns
const bgSyncPluginPost = new BackgroundSyncPlugin('api-queue-post', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
})
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkOnly({
    plugins: [bgSyncPluginPost]
  }),
  'POST'
)

const bgSyncPluginPatch = new BackgroundSyncPlugin('api-queue-patch', {
  maxRetentionTime: 24 * 60
})
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkOnly({
    plugins: [bgSyncPluginPatch]
  }),
  'PATCH'
)

const bgSyncPluginDelete = new BackgroundSyncPlugin('api-queue-delete', {
  maxRetentionTime: 24 * 60
})
registerRoute(
  /^https:\/\/.*\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkOnly({
    plugins: [bgSyncPluginDelete]
  }),
  'DELETE'
)

// Web Push Notifications
self.addEventListener('push', (event: any) => {
  const data = event.data?.json() ?? { title: 'New Notification', body: 'You have a new update in LISTIFY.' }
  
  const options = {
    body: data.body,
    icon: '/icon-192x192.png',
    badge: '/icon-192x192.png',
    data: { url: data.url || '/' }
  }

  event.waitUntil(self.registration.showNotification(data.title, options))
})

self.addEventListener('notificationclick', (event: any) => {
  event.notification.close()
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList: any) => {
      // If a window is already open, focus it
      for (const client of clientList) {
        if (client.url === event.notification.data.url && 'focus' in client) {
          return client.focus()
        }
      }
      // Otherwise, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(event.notification.data.url)
      }
    })
  )
})
